language: rust
rust:
  - 1.2.0
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo doc
  - cargo test --verbose
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench --verbose;
    fi
