[package]
name = "fst"
version = "0.1.0"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = """
Use finite state transducers to compactly represents sets or maps of many
strings (> 1 billion is possible).
"""
documentation = "http://burntsushi.net/rustdoc/fst/"
homepage = "https://github.com/BurntSushi/fst"
repository = "https://github.com/BurntSushi/fst"
readme = "README.md"
keywords = ["search", "information", "retrieval", "dictionary", "map"]
license = "Unlicense/MIT"

[[bin]]
name = "fst"
path = "src/bin/main.rs"

[dependencies]
byteorder = "*"

[dev-dependencies]
quickcheck = "0.2"
rand = "0.3"

[profile.release]
debug = true
