[package]
name = "fst-bin"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]

[[bin]]
name = "fst"

[dependencies]
bit-set = "0.2"
csv = "0.14"
docopt = "0.6"
fst = { path = "..", version = "0.1" }
rustc-serialize = "0.3"
